/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v12.0
processor: MKV42F64xxx16
package_id: MKV42F64VLF16
mcu_data: ksdk2_0
processor_version: 12.0.0
pin_labels:
- {pin_num: '13', pin_signal: ADCA_CH4/CMP1_IN5/CMP0_IN5/PTE29/FTM0_CH2/FTM_CLKIN0, label: Hall_A}
- {pin_num: '14', pin_signal: CMP1_IN3/ADCA_CH5/PTE30/FTM0_CH3/FTM_CLKIN1, label: Hall_B}
- {pin_num: '41', pin_signal: PTD0/LLWU_P12/SPI0_PCS0/FTM3_CH0/FTM0_CH0, label: PWM_W_L}
- {pin_num: '42', pin_signal: ADCA_CH7f/PTD1/SPI0_SCK/FTM3_CH1/FTM0_CH1, label: PWM_W_H}
- {pin_num: '43', pin_signal: PTD2/LLWU_P13/SPI0_SOUT/FTM3_CH2/FTM0_CH2/I2C0_SCL, label: PWM_V_L}
- {pin_num: '44', pin_signal: PTD3/SPI0_SIN/FTM3_CH3/FTM0_CH3/I2C0_SDA, label: PWM_V_H}
- {pin_num: '45', pin_signal: PTD4/LLWU_P14/SPI0_PCS1/UART0_RTS_b/FTM0_CH4/EWM_IN/SPI0_PCS0, label: PWM_U_L}
- {pin_num: '46', pin_signal: ADCA_CH6g/PTD5/SPI0_PCS2/UART0_CTS_b/UART0_COL_b/FTM0_CH5/EWM_OUT_b/SPI0_SCK, label: PWM_U_H}
- {pin_num: '47', pin_signal: ADCA_CH7g/PTD6/LLWU_P15/SPI0_PCS3/UART0_RX/FTM0_CH6/FTM1_CH0/FTM0_FLT0/SPI0_SOUT, label: ADC_IPM_temp}
- {pin_num: '48', pin_signal: PTD7/UART0_TX/FTM0_CH7/FTM1_CH1/FTM0_FLT1/SPI0_SIN, label: Relay_trigger}
- {pin_num: '3', pin_signal: ADCA_CH0/PTE16/SPI0_PCS0/UART1_TX/FTM_CLKIN0/FTM0_FLT3, label: W_current}
- {pin_num: '6', pin_signal: ADCB_CH1/PTE19/SPI0_SIN/UART1_RTS_b/I2C0_SCL/CMP3_OUT, label: U_current}
- {pin_num: '4', pin_signal: ADCA_CH1/PTE17/LLWU_P19/SPI0_SCK/UART1_RX/FTM_CLKIN1/LPTMR0_ALT3, label: V_current}
- {pin_num: '28', pin_signal: ADCB_CH3/PTB1/I2C0_SDA/FTM1_CH1/FTM0_FLT2/EWM_IN/FTM1_QD_PHB/UART0_TX, label: DC_Bus}
- {pin_num: '15', pin_signal: ADCB_CH4/PTE24/FTM0_CH0/XBARIN2/I2C0_SCL/EWM_OUT_b/XBAROUT4, label: Hall_C}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '48', peripheral: GPIOD, signal: 'GPIO, 7', pin_signal: PTD7/UART0_TX/FTM0_CH7/FTM1_CH1/FTM0_FLT1/SPI0_SIN, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '20', peripheral: JTAG, signal: JTAG_TMS_SWD_DIO, pin_signal: PTA3/UART0_RTS_b/FTM0_CH0/XBARIN9/EWM_OUT/JTAG_TMS/SWD_DIO}
  - {pin_num: '47', peripheral: ADC, signal: 'ADCA, 7', pin_signal: ADCA_CH7g/PTD6/LLWU_P15/SPI0_PCS3/UART0_RX/FTM0_CH6/FTM1_CH0/FTM0_FLT0/SPI0_SOUT}
  - {pin_num: '42', peripheral: FTM0, signal: 'CH, 1', pin_signal: ADCA_CH7f/PTD1/SPI0_SCK/FTM3_CH1/FTM0_CH1, direction: OUTPUT}
  - {pin_num: '45', peripheral: FTM0, signal: 'CH, 4', pin_signal: PTD4/LLWU_P14/SPI0_PCS1/UART0_RTS_b/FTM0_CH4/EWM_IN/SPI0_PCS0, direction: OUTPUT}
  - {pin_num: '46', peripheral: FTM0, signal: 'CH, 5', pin_signal: ADCA_CH6g/PTD5/SPI0_PCS2/UART0_CTS_b/UART0_COL_b/FTM0_CH5/EWM_OUT_b/SPI0_SCK, direction: OUTPUT}
  - {pin_num: '17', peripheral: JTAG, signal: JTAG_TCLK_SWD_CLK, pin_signal: PTA0/UART0_CTS_b/UART0_COL_b/FTM0_CH5/XBARIN4/EWM_IN/JTAG_TCLK/SWD_CLK}
  - {pin_num: '3', peripheral: ADC, signal: 'ADCA, 0', pin_signal: ADCA_CH0/PTE16/SPI0_PCS0/UART1_TX/FTM_CLKIN0/FTM0_FLT3}
  - {pin_num: '6', peripheral: ADC, signal: 'ADCB, 1', pin_signal: ADCB_CH1/PTE19/SPI0_SIN/UART1_RTS_b/I2C0_SCL/CMP3_OUT}
  - {pin_num: '4', peripheral: ADC, signal: 'ADCA, 1', pin_signal: ADCA_CH1/PTE17/LLWU_P19/SPI0_SCK/UART1_RX/FTM_CLKIN1/LPTMR0_ALT3}
  - {pin_num: '28', peripheral: ADC, signal: 'ADCB, 3', pin_signal: ADCB_CH3/PTB1/I2C0_SDA/FTM1_CH1/FTM0_FLT2/EWM_IN/FTM1_QD_PHB/UART0_TX}
  - {pin_num: '41', peripheral: FTM3, signal: 'CH, 0', pin_signal: PTD0/LLWU_P12/SPI0_PCS0/FTM3_CH0/FTM0_CH0, direction: OUTPUT}
  - {pin_num: '43', peripheral: FTM3, signal: 'CH, 2', pin_signal: PTD2/LLWU_P13/SPI0_SOUT/FTM3_CH2/FTM0_CH2/I2C0_SCL, direction: OUTPUT}
  - {pin_num: '44', peripheral: FTM3, signal: 'CH, 3', pin_signal: PTD3/SPI0_SIN/FTM3_CH3/FTM0_CH3/I2C0_SDA, direction: OUTPUT}
  - {pin_num: '13', peripheral: GPIOE, signal: 'GPIO, 29', pin_signal: ADCA_CH4/CMP1_IN5/CMP0_IN5/PTE29/FTM0_CH2/FTM_CLKIN0, direction: INPUT, gpio_interrupt: kPORT_InterruptOrDMADisabled,
    digital_filter: disable}
  - {pin_num: '14', peripheral: GPIOE, signal: 'GPIO, 30', pin_signal: CMP1_IN3/ADCA_CH5/PTE30/FTM0_CH3/FTM_CLKIN1, direction: INPUT, gpio_interrupt: kPORT_InterruptOrDMADisabled}
  - {pin_num: '15', peripheral: GPIOE, signal: 'GPIO, 24', pin_signal: ADCB_CH4/PTE24/FTM0_CH0/XBARIN2/I2C0_SCL/EWM_OUT_b/XBAROUT4, direction: INPUT, gpio_interrupt: kPORT_InterruptOrDMADisabled}
  - {pin_num: '18', peripheral: UART0, signal: RX, pin_signal: PTA1/UART0_RX/FTM0_CH6/CMP0_OUT/FTM1_CH1/JTAG_TDI}
  - {pin_num: '19', peripheral: UART0, signal: TX, pin_signal: PTA2/UART0_TX/FTM0_CH7/CMP1_OUT/FTM1_CH0/JTAG_TDO/TRACE_SWO}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Port B Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);
    /* Port D Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortD);
    /* Port E Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortE);

    gpio_pin_config_t gpiod_pin48_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTD7 (pin 48)  */
    GPIO_PinInit(GPIOD, 7U, &gpiod_pin48_config);

    gpio_pin_config_t gpioe_pin15_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTE24 (pin 15)  */
    GPIO_PinInit(GPIOE, 24U, &gpioe_pin15_config);

    gpio_pin_config_t gpioe_pin13_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTE29 (pin 13)  */
    GPIO_PinInit(GPIOE, 29U, &gpioe_pin13_config);

    gpio_pin_config_t gpioe_pin14_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTE30 (pin 14)  */
    GPIO_PinInit(GPIOE, 30U, &gpioe_pin14_config);

    /* PORTA0 (pin 17) is configured as JTAG_TCLK */
    PORT_SetPinMux(PORTA, 0U, kPORT_MuxAlt7);

    /* PORTA1 (pin 18) is configured as UART0_RX */
    PORT_SetPinMux(PORTA, 1U, kPORT_MuxAlt2);

    /* PORTA2 (pin 19) is configured as UART0_TX */
    PORT_SetPinMux(PORTA, 2U, kPORT_MuxAlt2);

    /* PORTA3 (pin 20) is configured as JTAG_TMS */
    PORT_SetPinMux(PORTA, 3U, kPORT_MuxAlt7);

    /* PORTB1 (pin 28) is configured as ADCB_CH3 */
    PORT_SetPinMux(PORTB, 1U, kPORT_PinDisabledOrAnalog);

    /* PORTD0 (pin 41) is configured as FTM3_CH0 */
    PORT_SetPinMux(PORTD, 0U, kPORT_MuxAlt4);

    /* PORTD1 (pin 42) is configured as FTM0_CH1 */
    PORT_SetPinMux(PORTD, 1U, kPORT_MuxAlt5);

    /* PORTD2 (pin 43) is configured as FTM3_CH2 */
    PORT_SetPinMux(PORTD, 2U, kPORT_MuxAlt4);

    /* PORTD3 (pin 44) is configured as FTM3_CH3 */
    PORT_SetPinMux(PORTD, 3U, kPORT_MuxAlt4);

    /* PORTD4 (pin 45) is configured as FTM0_CH4 */
    PORT_SetPinMux(PORTD, 4U, kPORT_MuxAlt4);

    /* PORTD5 (pin 46) is configured as FTM0_CH5 */
    PORT_SetPinMux(PORTD, 5U, kPORT_MuxAlt4);

    /* PORTD6 (pin 47) is configured as ADCA_CH7g */
    PORT_SetPinMux(PORTD, 6U, kPORT_PinDisabledOrAnalog);

    /* PORTD7 (pin 48) is configured as PTD7 */
    PORT_SetPinMux(PORTD, 7U, kPORT_MuxAsGpio);

    /* PORTE16 (pin 3) is configured as ADCA_CH0 */
    PORT_SetPinMux(PORTE, 16U, kPORT_PinDisabledOrAnalog);

    /* PORTE17 (pin 4) is configured as ADCA_CH1 */
    PORT_SetPinMux(PORTE, 17U, kPORT_PinDisabledOrAnalog);

    /* PORTE19 (pin 6) is configured as ADCB_CH1 */
    PORT_SetPinMux(PORTE, 19U, kPORT_PinDisabledOrAnalog);

    /* PORTE24 (pin 15) is configured as PTE24 */
    PORT_SetPinMux(PORTE, 24U, kPORT_MuxAsGpio);

    /* Interrupt configuration on PORTE24 (pin 15): Interrupt/DMA request is disabled */
    PORT_SetPinInterruptConfig(PORTE, 24U, kPORT_InterruptOrDMADisabled);

    /* PORTE29 (pin 13) is configured as PTE29 */
    PORT_SetPinMux(PORTE, 29U, kPORT_MuxAsGpio);

    /* Interrupt configuration on PORTE29 (pin 13): Interrupt/DMA request is disabled */
    PORT_SetPinInterruptConfig(PORTE, 29U, kPORT_InterruptOrDMADisabled);

    /* PORTE30 (pin 14) is configured as PTE30 */
    PORT_SetPinMux(PORTE, 30U, kPORT_MuxAsGpio);

    /* Interrupt configuration on PORTE30 (pin 14): Interrupt/DMA request is disabled */
    PORT_SetPinInterruptConfig(PORTE, 30U, kPORT_InterruptOrDMADisabled);

    SIM->ADCOPT = ((SIM->ADCOPT &
                    /* Mask bits to zero which are setting */
                    (~(SIM_ADCOPT_ADCACH7SEL_MASK)))

                   /* ADCA MUX1 selection for ADCA channel 7: ADCA MUX1's channel g. */
                   | SIM_ADCOPT_ADCACH7SEL(ADCOPT_ADCACH7SEL_CH_G));

    SIM->SOPT5 = ((SIM->SOPT5 &
                   /* Mask bits to zero which are setting */
                   (~(SIM_SOPT5_UART0TXSRC_MASK | SIM_SOPT5_UART0RXSRC_MASK)))

                  /* UART 0 transmit data source select: UART0_TX pin. */
                  | SIM_SOPT5_UART0TXSRC(SOPT5_UART0TXSRC_UART_TX)

                  /* UART 0 receive data source select: UART0_RX pin. */
                  | SIM_SOPT5_UART0RXSRC(SOPT5_UART0RXSRC_UART_RX));

    SIM->SOPT8 =
        ((SIM->SOPT8 &
          /* Mask bits to zero which are setting */
          (~(SIM_SOPT8_FTM0OCH1SRC_MASK | SIM_SOPT8_FTM0OCH4SRC_MASK | SIM_SOPT8_FTM0OCH5SRC_MASK | SIM_SOPT8_FTM3OCH0SRC_MASK | SIM_SOPT8_FTM3OCH2SRC_MASK | SIM_SOPT8_FTM3OCH3SRC_MASK)))

         /* FTM0 channel 1 output source: FTM0_CH1 pin is output of FTM0 channel 1 output. */
         | SIM_SOPT8_FTM0OCH1SRC(SOPT8_FTM0OCH1SRC_FTM)

         /* FTM0 channel 4 output source: FTM0_CH4 pin is output of FTM0 channel 4 output. */
         | SIM_SOPT8_FTM0OCH4SRC(SOPT8_FTM0OCH4SRC_FTM)

         /* FTM0 channel 5 output source: FTM0_CH5 pin is output of FTM0 channel 5 output. */
         | SIM_SOPT8_FTM0OCH5SRC(SOPT8_FTM0OCH5SRC_FTM)

         /* FTM3 channel 0 output source: FTM3_CH0 pin is output of FTM3 channel 0 output. */
         | SIM_SOPT8_FTM3OCH0SRC(SOPT8_FTM3OCH0SRC_FTM)

         /* FTM3 channel 2 output source: FTM3_CH2 pin is output of FTM3 channel 2 output. */
         | SIM_SOPT8_FTM3OCH2SRC(SOPT8_FTM3OCH2SRC_FTM)

         /* FTM3 channel 3 output source: FTM3_CH3 pin is output of FTM3 channel 3 output. */
         | SIM_SOPT8_FTM3OCH3SRC(SOPT8_FTM3OCH3SRC_FTM));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
