/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief ADCA MUX1 selection for ADCA channel 7: ADCA MUX1's channel g. */
#define ADCOPT_ADCACH7SEL_CH_G 0x06u
/*!
 * @brief UART 0 receive data source select: UART0_RX pin */
#define SOPT5_UART0RXSRC_UART_RX 0x00u
/*!
 * @brief UART 0 transmit data source select: UART0_TX pin */
#define SOPT5_UART0TXSRC_UART_TX 0x00u
/*!
 * @brief FTM0 channel 1 output source: FTM0_CH1 pin is output of FTM0 channel 1 output */
#define SOPT8_FTM0OCH1SRC_FTM 0x00u
/*!
 * @brief FTM0 channel 4 output source: FTM0_CH4 pin is output of FTM0 channel 4 output */
#define SOPT8_FTM0OCH4SRC_FTM 0x00u
/*!
 * @brief FTM0 channel 5 output source: FTM0_CH5 pin is output of FTM0 channel 5 output */
#define SOPT8_FTM0OCH5SRC_FTM 0x00u
/*!
 * @brief FTM3 channel 0 output source: FTM3_CH0 pin is output of FTM3 channel 0 output */
#define SOPT8_FTM3OCH0SRC_FTM 0x00u
/*!
 * @brief FTM3 channel 2 output source: FTM3_CH2 pin is output of FTM3 channel 2 output */
#define SOPT8_FTM3OCH2SRC_FTM 0x00u
/*!
 * @brief FTM3 channel 3 output source: FTM3_CH3 pin is output of FTM3 channel 3 output */
#define SOPT8_FTM3OCH3SRC_FTM 0x00u

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
